### PR TITLE
support macos sequoia

### PR DESCRIPTION
**Pull request by adammlr**

### CODE REVIEW

**Comment by ProLoser** [comment]
@bpasero are you still active? You know your `issues` feature is not enabled?

**Comment by bpasero** [comment]
Thanks, I have enabled "Issues". Can the fix be explained?

**Comment by adammlr** [comment]
In my testing, creating the tmp folder on MacOS Sequioa will create a 2nd level folder to place the temporary file.  If the recursive parameter is not added the mkdir call will fail.

**Comment by bpasero** [comment]
I need to verify and test this with an installation of Sequoia.

**Comment by bpasero** [comment]
I see no issues in macOS 15.

**Pull request closed without merging**
